In [1]:
import csv
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("C:/Mydisk/workspaces/SQL_project/Steam_FINAL.csv")
df.head()

,app_id,name,release_date,price_usd,discount_pct,is_discounted,is_free,review_score_pct,total_reviews,estimated_owners,...,steam_supported_os,steam_interface_languages,steam_subtitle_languages,steam_audio_languages,steam_minimum_ram_gb,steam_minimum_storage_gb,steam_metacritic_score,steam_dlc_count,steam_age_rating_system,steam_age_rating_value
0,730,Counter-Strike 2,2012-08-21,0.00,0,0,1,83,4980365,149410950,...,"[""Windows"", ""Linux""]","[""English"", ""Czech"", ""Danish"", ""Dutch"", ""Finni...",[],"[""English""]",8.0,85.0,NaN,1.0,USK,16
1,2868840,Slay the Spire 2,2026-03-05,24.99,0,0,0,97,49549,1486470,...,"[""Windows"", ""Mac"", ""Linux""]","[""English"", ""French"", ""Italian"", ""German"", ""Sp...",[],[],4.0,4.0,NaN,0.0,DEJUS,10
2,3321460,Crimson Desert,2026-03-19,69.99,0,0,0,0,0,0,...,"[""Windows"", ""Mac""]","[""English"", ""French"", ""Italian"", ""German"", ""Sp...","[""English"", ""French"", ""Italian"", ""German"", ""Sp...","[""English"", ""Korean"", ""Simplified Chinese""]",16.0,150.0,NaN,2.0,PEGI,18
3,3065800,Marathon,2026-03-05,39.99,0,0,0,90,24360,730800,...,"[""Windows""]","[""English"", ""French"", ""Italian"", ""German"", ""Sp...","[""English"", ""French"", ""Italian"", ""German"", ""Sp...","[""English"", ""French"", ""Italian"", ""German"", ""Sp...",8.0,NaN,NaN,3.0,ESRB,Teen
4,3764200,Resident Evil Requiem,2026-02-26,69.99,0,0,0,96,79667,2390010,...,"[""Windows""]","[""English"", ""French"", ""Italian"", ""German"", ""Sp...","[""English"", ""French"", ""Italian"", ""German"", ""Sp...","[""English"", ""French"", ""Italian"", ""German"", ""Sp...",16.0,NaN,92.0,3.0,ESRB,Mature 17+

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 935 entries, 0 to 934
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   app_id                     935 non-null    int64
 1   name                       935 non-null    object
 2   release_date               934 non-null    object
 3   price_usd                  935 non-null    float64
 4   discount_pct               935 non-null    int64
 5   is_discounted              935 non-null    int64
 6   is_free                    935 non-null    int64
 7   review_score_pct           935 non-null    int64
 8   total_reviews              935 non-null    int64
 9   estimated_owners           935 non-null    int64
 10  peak_24h_players           935 non-null    int64
 11  steam_official_genres      933 non-null    object
 12  steam_tags                 935 non-null    object
 13  steam_store_features       935 non-null    object
 14  steam_developer            935 non-null    object
 15  steam_publisher            934 non-null    object
 16  steam_supported_os         935 non-null    object
 17  steam_interface_languages  935 non-null    object
 18  steam_subtitle_languages   935 non-null    object
 19  steam_audio_languages      935 non-null    object
 20  steam_minimum_ram_gb       923 non-null    float64
 21  steam_minimum_storage_gb   883 non-null    float64
 22  steam_metacritic_score     292 non-null    float64
 23  steam_dlc_count            935 non-null    float64
 24  steam_age_rating_system    933 non-null    object
 25  steam_age_rating_value     933 non-null    object
dtypes: float64(5), int64(8), object(13)
memory usage: 190.0+ KB

In [4]:
need_columns=['app_id', 'name', 'release_date', 'price_usd', 'review_score_pct', 'total_reviews', 'estimated_owners', 
              'steam_official_genres', 'steam_developer']
df_need=df[need_columns].copy()
df_need.head()

,app_id,name,release_date,price_usd,review_score_pct,total_reviews,estimated_owners,steam_official_genres,steam_developer
0,730,Counter-Strike 2,2012-08-21,0.00,83,4980365,149410950,"[""Action"", ""Free To Play""]","[""Valve""]"
1,2868840,Slay the Spire 2,2026-03-05,24.99,97,49549,1486470,"[""Indie"", ""Strategy"", ""Early Access""]","[""Mega Crit""]"
2,3321460,Crimson Desert,2026-03-19,69.99,0,0,0,"[""Action"", ""Adventure""]","[""Pearl Abyss""]"
3,3065800,Marathon,2026-03-05,39.99,90,24360,730800,"[""Action""]","[""Bungie""]"
4,3764200,Resident Evil Requiem,2026-02-26,69.99,96,79667,2390010,"[""Action"", ""Adventure""]","[""CAPCOM Co., Ltd.""]"

In [5]:
df_need.isna().sum()

app_id                   0
name                     0
release_date             1
price_usd                0
review_score_pct         0
total_reviews            0
estimated_owners         0
steam_official_genres    2
steam_developer          0
dtype: int64

In [6]:
df_need=df_need.dropna()

In [7]:
df_need.isna().sum()

app_id                   0
name                     0
release_date             0
price_usd                0
review_score_pct         0
total_reviews            0
estimated_owners         0
steam_official_genres    0
steam_developer          0
dtype: int64

In [8]:
genres_table_column=['app_id', 'name', 'steam_official_genres']
df_genres=df[genres_table_column].copy()
df_genres.head()

    app_id                   name                  steam_official_genres
0      730       Counter-Strike 2             ["Action", "Free To Play"]
1  2868840       Slay the Spire 2  ["Indie", "Strategy", "Early Access"]
2  3321460         Crimson Desert                ["Action", "Adventure"]
3  3065800               Marathon                             ["Action"]
4  3764200  Resident Evil Requiem                ["Action", "Adventure"]

In [9]:
df_genres['steam_official_genres'] = (
    df_genres['steam_official_genres']
    .astype(str)
    .str.replace(r"[\[\]'\"]", "", regex=True))
df_genres['steam_official_genres']=df_genres['steam_official_genres'].str.split(',')
df_genres=df_genres.explode('steam_official_genres')
df_genres['steam_official_genres']=df_genres['steam_official_genres'].astype(str).str.strip()

df_genres.head(10)

    app_id                   name steam_official_genres
0      730       Counter-Strike 2                Action
0      730       Counter-Strike 2          Free To Play
1  2868840       Slay the Spire 2                 Indie
1  2868840       Slay the Spire 2              Strategy
1  2868840       Slay the Spire 2          Early Access
2  3321460         Crimson Desert                Action
2  3321460         Crimson Desert             Adventure
3  3065800               Marathon                Action
4  3764200  Resident Evil Requiem                Action
4  3764200  Resident Evil Requiem             Adventure

In [10]:
final_columns=['app_id', 'name', 'release_date', 'price_usd', 'review_score_pct', 'total_reviews', 'estimated_owners', 'steam_developer']
df_final=df_need[final_columns].copy()
df_final.head()

,app_id,name,release_date,price_usd,review_score_pct,total_reviews,estimated_owners,steam_developer
0,730,Counter-Strike 2,2012-08-21,0.00,83,4980365,149410950,"[""Valve""]"
1,2868840,Slay the Spire 2,2026-03-05,24.99,97,49549,1486470,"[""Mega Crit""]"
2,3321460,Crimson Desert,2026-03-19,69.99,0,0,0,"[""Pearl Abyss""]"
3,3065800,Marathon,2026-03-05,39.99,90,24360,730800,"[""Bungie""]"
4,3764200,Resident Evil Requiem,2026-02-26,69.99,96,79667,2390010,"[""CAPCOM Co., Ltd.""]"

In [11]:
df_final['steam_developer'] = (
    df_final['steam_developer']
    .astype(str)
    .str.replace(r"[\[\]'\"]", "", regex=True))
df_final.head()

,app_id,name,release_date,price_usd,review_score_pct,total_reviews,estimated_owners,steam_developer
0,730,Counter-Strike 2,2012-08-21,0.00,83,4980365,149410950,Valve
1,2868840,Slay the Spire 2,2026-03-05,24.99,97,49549,1486470,Mega Crit
2,3321460,Crimson Desert,2026-03-19,69.99,0,0,0,Pearl Abyss
3,3065800,Marathon,2026-03-05,39.99,90,24360,730800,Bungie
4,3764200,Resident Evil Requiem,2026-02-26,69.99,96,79667,2390010,"CAPCOM Co., Ltd."

In [12]:
df_final['review_score_negative']=100-df_final['review_score_pct']
df_final.head()

,app_id,name,release_date,price_usd,review_score_pct,total_reviews,estimated_owners,steam_developer,review_score_negative
0,730,Counter-Strike 2,2012-08-21,0.00,83,4980365,149410950,Valve,17
1,2868840,Slay the Spire 2,2026-03-05,24.99,97,49549,1486470,Mega Crit,3
2,3321460,Crimson Desert,2026-03-19,69.99,0,0,0,Pearl Abyss,100
3,3065800,Marathon,2026-03-05,39.99,90,24360,730800,Bungie,10
4,3764200,Resident Evil Requiem,2026-02-26,69.99,96,79667,2390010,"CAPCOM Co., Ltd.",4

In [15]:
df_final=df_final[df_final.total_reviews != 0]
df_final.head(10)

,app_id,name,release_date,price_usd,review_score_pct,total_reviews,estimated_owners,steam_developer,review_score_negative
0,730,Counter-Strike 2,2012-08-21,0.00,83,4980365,149410950,Valve,17
1,2868840,Slay the Spire 2,2026-03-05,24.99,97,49549,1486470,Mega Crit,3
3,3065800,Marathon,2026-03-05,39.99,90,24360,730800,Bungie,10
4,3764200,Resident Evil Requiem,2026-02-26,69.99,96,79667,2390010,"CAPCOM Co., Ltd.",4
5,2157830,John Carpenter's Toxic Commando,2026-03-12,39.99,83,2765,82950,Saber Interactive,17
6,1144200,Ready or Not,2023-12-13,49.99,85,243810,7314300,VOID Interactive,15
7,1172470,Apex Legends™,2020-11-04,0.00,65,1577,47310,Respawn,35
8,1808500,ARC Raiders,2025-10-30,39.99,79,264150,7924500,Embark Studios,21
9,2852190,Monster Hunter Stories 3: Twisted Reflection,2026-03-12,69.99,75,1570,47100,"CAPCOM Co., Ltd.",25
10,1167630,Teardown,2022-04-21,14.99,94,115777,3473310,Tuxedo Labs,6

In [16]:
df_final['name'] = df_final['name'].astype(str).str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)
df_final['steam_developer'] = df_final['steam_developer'].astype(str).str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)
df_final.head(20)

,app_id,name,release_date,price_usd,review_score_pct,total_reviews,estimated_owners,steam_developer,review_score_negative
0,730,CounterStrike 2,2012-08-21,0.00,83,4980365,149410950,Valve,17
1,2868840,Slay the Spire 2,2026-03-05,24.99,97,49549,1486470,Mega Crit,3
3,3065800,Marathon,2026-03-05,39.99,90,24360,730800,Bungie,10
4,3764200,Resident Evil Requiem,2026-02-26,69.99,96,79667,2390010,CAPCOM Co Ltd,4
5,2157830,John Carpenters Toxic Commando,2026-03-12,39.99,83,2765,82950,Saber Interactive,17
6,1144200,Ready or Not,2023-12-13,49.99,85,243810,7314300,VOID Interactive,15
7,1172470,Apex Legends,2020-11-04,0.00,65,1577,47310,Respawn,35
8,1808500,ARC Raiders,2025-10-30,39.99,79,264150,7924500,Embark Studios,21
9,2852190,Monster Hunter Stories 3 Twisted Reflection,2026-03-12,69.99,75,1570,47100,CAPCOM Co Ltd,25
10,1167630,Teardown,2022-04-21,14.99,94,115777,3473310,Tuxedo Labs,6
11,2552430,KINGDOM HEARTS HD 1525 ReMIX,2024-06-13,24.99,89,8167,245010,Square Enix,11
12,4069520,Super Battle Golf,2026-02-19,7.99,95,4025,120750,Brimstone,5
14,1222670,The Sims 4,2020-06-18,0.00,79,82661,2479830,Maxis,21
15,2778610,Over The Top WWI,2026-03-06,16.26,88,3572,107160,Flying Squirrel Entertainment,12
16,359550,Tom Clancys Rainbow Six Siege,2015-12-01,0.00,75,1234092,37022760,Ubisoft Montreal,25
17,553850,HELLDIVERS 2,2024-02-08,39.99,70,807861,24235830,Arrowhead Game Studios,30
18,230410,Warframe,2013-03-25,0.00,90,2880,86400,Digital Extremes,10
19,2357570,Overwatch,2023-08-10,0.00,60,257,7710,Blizzard Entertainment Inc,40
20,236390,War Thunder,2013-08-15,0.00,76,1961,58830,Gaijin Entertainment,24
21,3472040,NBA 2K26,2025-09-04,19.99,74,12634,379020,Visual Concepts,26

In [17]:
df_final.to_csv('game_table.csv', index=False)
df_genres.to_csv("genres_table.csv", index=False)